### ISSUE TITLE
httpx.PoolTimeout

### ISSUE THREAD

**Issue by Windsland52** [alphaply/DouyinComments#7]
Enter the aweme_id: 7408850305816874240
Fetching comments: 479comment [00:48,  9.90comment/s]
Found 479 comments.
Fetching replies:  68%|██████████████████████████████████████▉                  | 327/479 [05:52<02:44,  1.08s/comment]
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\connection_pool.py", line 192, in handle_async_request
    connection = await pool_request.wait_for_connection(timeout=timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\connection_pool.py", line 35, in wait_for_connection
    await self._connection_acquired.wait(timeout=timeout)
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_synchronization.py", line 148, in wait
    with map_exceptions(anyio_exc_map):
  File "C:\ProgramData\miniconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 148, in <module>
    asyncio.run(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 139, in main
    all_replies = await fetch_all_replies_async(all_comments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 77, in fetch_all_replies_async
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 60, in fetch_replies_for_comment
    response = await get_replies_async(client, comment_id, cursor=str(cursor))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 48, in get_replies_async
    response = await client.get(reply_url, params=params, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\ProgramData\miniconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

**Comment by Windsland52** [comment]
gpt4o回答参考
该错误提示了 httpx.PoolTimeout，这是由于连接池中的连接超时，可能是由于在短时间内发送了大量请求，导致没有足够的连接可用。

解决方法：
增加连接池大小：在使用 httpx.AsyncClient 时，可以通过设置 limits 参数来增加连接池的大小和超时时间。例如：

```python
import httpx

limits = httpx.Limits(max_connections=100, max_keepalive_connections=20)
timeout = httpx.Timeout(10.0)  # 设置超时时间
async with httpx.AsyncClient(limits=limits, timeout=timeout) as client:
    # 你的请求代码
```
减少并发请求数量：使用 asyncio.Semaphore 限制同时进行的请求数。这样可以避免过多的并发请求导致连接池超时。

```python
import asyncio
import httpx

semaphore = asyncio.Semaphore(10)  # 限制同时进行的请求数为10

async def fetch_replies_for_comment(client, comment_id, cursor):
    async with semaphore:
        response = await get_replies_async(client, comment_id, cursor=str(cursor))
        return response
```
调整请求间隔：可以在每个请求之间增加一些延迟时间，避免短时间内发送大量请求。

```python
import asyncio

async def fetch_replies_for_comment(client, comment_id, cursor):
    await asyncio.sleep(0.5)  # 增加延迟时间，0.5秒
    response = await get_replies_async(client, comment_id, cursor=str(cursor))
    return response
```
处理重试逻辑：为请求添加重试机制，防止请求失败时立即退出。可以使用 httpx 的重试机制或者自己实现重试逻辑。

```python
import httpx
from httpx import RequestError

async def get_replies_async(client, comment_id, cursor):
    retries = 3
    for i in range(retries):
        try:
            response = await client.get(reply_url, params=params, headers=headers)
            return response
        except RequestError:
            if i < retries - 1:
                await asyncio.sleep(1)  # 在重试前等待1秒
            else:
                raise
```
通过这些方法可以有效避免由于并发请求过多或连接池限制导致的超时问题。

**Comment by Windsland52** [comment]
重试后结果相同，68% 327/479

**Comment by alphaply** [comment]
这是他的限制，没有办法，只能加大延迟

**Comment by alphaply** [comment]
或者更换ip

**Comment by Windsland52** [comment]
> 这是他的限制，没有办法，只能加大延迟

okk,谢谢，可以考虑加个延迟处理。

**Comment by alphaply** [comment]
其实最有效的是换个ip用户之类的

**Comment by Windsland52** [comment]
> 其实最有效的是换个ip用户之类的

好，我研究一下

**Comment by alphaply** [comment]
你加timeout参数试一下，不是sleep

**Comment by alphaply** [comment]
我等会commit一份新的

**Comment by alphaply** [comment]
Fetching comments: 486comment [00:45, 10.73comment/s]
Found 486 comments.
Fetching replies: 100%|██████████| 486/486 [05:10<00:00,  1.56comment/s]
Found 357 replies
Found 843 in totals
done!

**Comment by Windsland52** [comment]
> 你加timeout参数试一下，不是sleep

试了下，光加timeout不行，还要加limits。
limits = httpx.Limits(max_connections=1, max_keepalive_connections=1)可以，
limits = httpx.Limits(max_connections=100, max_keepalive_connections=20)不行，会报httpx.ConnectTimeout。
timeout = httpx.Timeout(10.0) 保持不变就行

**Comment by alphaply** [comment]
我加了信号量控制

**Comment by Windsland52** [comment]
> 我加了信号量控制

改完试了下
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\http_proxy.py", line 344, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\http11.py", line 143, in handle_async_request
    raise exc
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore\_async\http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 162, in <module>
    asyncio.run(main())
  File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 158, in main
    await asyncio.gather(*tasks)
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 146, in process_aweme_id
    all_replies = await fetch_all_replies_async(all_comments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 82, in fetch_all_replies_async
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 63, in fetch_replies_for_comment
    response = await get_replies_async(client, semaphore, comment_id, cursor=str(cursor))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 52, in get_replies_async
    response = await client.get(reply_url, params=params, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\ProgramData\miniconda3\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\ProgramData\miniconda3\Lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by Windsland52** [comment]
> > 我加了信号量控制
> 
> 改完试了下 Traceback (most recent call last): File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_transports\default.py", line 69, in map_httpcore_exceptions yield File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_transports\default.py", line 373, in handle_async_request resp = await self._pool.handle_async_request(req) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\connection_pool.py", line 216, in handle_async_request raise exc from None File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\connection_pool.py", line 196, in handle_async_request response = await connection.handle_async_request( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\http_proxy.py", line 344, in handle_async_request return await self._connection.handle_async_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\http11.py", line 143, in handle_async_request raise exc File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\http11.py", line 113, in handle_async_request ) = await self._receive_response_headers(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\http11.py", line 186, in _receive_response_headers event = await self._receive_event(timeout=timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpcore_async\http11.py", line 238, in _receive_event raise RemoteProtocolError(msg) httpcore.RemoteProtocolError: Server disconnected without sending a response.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 162, in asyncio.run(main()) File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 158, in main await asyncio.gather(*tasks) File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 146, in process_aweme_id all_replies = await fetch_all_replies_async(all_comments) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 82, in fetch_all_replies_async results = await asyncio.gather(*tasks) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 63, in fetch_replies_for_comment response = await get_replies_async(client, semaphore, comment_id, cursor=str(cursor)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\DELL\Desktop\github\DouyinComments\main.py", line 52, in get_replies_async response = await client.get(reply_url, params=params, headers=headers) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1801, in get return await self.request( ^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1574, in request return await self.send(request, auth=auth, follow_redirects=follow_redirects) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1661, in send response = await self._send_handling_auth( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1689, in _send_handling_auth response = await self._send_handling_redirects( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1726, in _send_handling_redirects response = await self._send_single_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_client.py", line 1763, in _send_single_request response = await transport.handle_async_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_transports\default.py", line 372, in handle_async_request with map_httpcore_exceptions(): File "C:\ProgramData\miniconda3\Lib\contextlib.py", line 155, in **exit** self.gen.throw(typ, value, traceback) File "C:\ProgramData\miniconda3\Lib\site-packages\httpx_transports\default.py", line 86, in map_httpcore_exceptions raise mapped_exc(message) from exc httpx.RemoteProtocolError: Server disconnected without sending a response.

这是我改过的代码(Windsland52/DouyinComments)[https://github.com/Windsland52/DouyinComments]

**Comment by Windsland52** [comment]
> 7408850305816874240

ok了，我去掉main函数的异步就行了
